### ISSUE TITLE
Enable test coverage reporting to Code Climate in GH

### ISSUE THREAD

**Issue by paolobrasolin** [paolobrasolin/mnogootex#5]
For reference, here is the old TravisCI configuration:

```yaml
language: ruby
cache: bundler
rvm:
  - 2.5
  - 2.4
  - 2.3
env:
  global:
    - CC_TEST_REPORTER_ID=890ed5ee01002c7149920883256f8e4790000127faa9ddf14d86dd3ceb3b8179
sudo: false
before_install: gem install bundler --no-doc
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - COVERAGE=true bundle exec rake spec:rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
branches:
  only:
  - master
```
